2020-03-27 11:35:45,919 ERROR: Exception on /index [GET] [in /home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/penciledge/Desktop/FlaskApp/app/routes.py", line 29, in index
    return render_template('index.html', title='Home', form=form,
NameError: name 'form' is not defined
2020-03-27 11:36:20,909 INFO: FlaskApp startup [in /home/penciledge/Desktop/FlaskApp/app/__init__.py:59]
2020-03-27 11:36:27,131 ERROR: Exception on /index [GET] [in /home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/penciledge/Desktop/FlaskApp/app/routes.py", line 31, in index
    prev_url=prev_url)
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/jinja2/loaders.py", line 129, in load
    code = environment.compile(source, name, filename)
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/penciledge/Desktop/FlaskApp/app/templates/index.html", line 39, in template
    <a href="{{ next_url or '#' }}">
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2020-03-27 11:39:57,749 INFO: FlaskApp startup [in /home/penciledge/Desktop/FlaskApp/app/__init__.py:59]
2020-03-27 11:40:06,417 ERROR: Exception on /index [GET] [in /home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/penciledge/Desktop/FlaskApp/app/routes.py", line 38, in index
    prev_url=prev_url)
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/jinja2/loaders.py", line 129, in load
    code = environment.compile(source, name, filename)
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/penciledge/.virtualenvs/FlaskApp-2SbuFn8L/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/penciledge/Desktop/FlaskApp/app/templates/index.html", line 39, in template
    <a href="{{ next_url or '#' }}">
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2020-03-27 11:44:33,108 INFO: FlaskApp startup [in /home/penciledge/Desktop/FlaskApp/app/__init__.py:59]
